version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "abuhamza"
    assignees:
      - "abuhamza"
    commit-message:
      prefix: "security"
      prefix-development: "dev-deps"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 3
    reviewers:
      - "abuhamza"
    assignees:
      - "abuhamza"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "ci"
      - "github-actions"